### ISSUE TITLE
1.3.9 Disables Save in Netbeans editor

### ISSUE THREAD

**Issue by sdf-cnicorp** [kelemen/netbeans-gradle-project#296]
When version 1.3.9 is installed in NB 8.2, the save button no longer saves changes. The log shows an exception:
Caused: org.netbeans.gradle.model.util.TransferableExceptionWrapper: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.netbeans.gradle.javaee.jpa.model.NbJpaModelBuilder

Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_65; Java HotSpot(TM) 64-Bit Server VM 25.65-b01
Runtime: Java(TM) SE Runtime Environment 1.8.0_65-b17
System: Mac OS X version 10.11.6 running on x86_64; UTF-8; en_US (nb)
User directory: /Users/sdf/Library/Application Support/NetBeans/8.2
Cache directory: /Users/sdf/Library/Caches/NetBeans/8.2

**Comment by sdf-cnicorp** [comment]
Netbeans log file
[messages.log.zip](https://github.com/kelemen/netbeans-gradle-project/files/519902/messages.log.zip)

**Comment by sdf-cnicorp** [comment]
More info:
I removed the Gradle EE plugin, which eliminated the ClassNotFound exception. However, as the attached log show there is still a problem.

I have several projects open in Netbeans at once. Some projects are gradle, some are ant, and some are maven based. As soon as the 1.3.9 gradle plugin was installed the Save button stopped working. The log shows 
java.lang.IllegalArgumentException: Not a Gradle project: /Users/sdf/Projects/AdDesk/apps/AdDeskBreeze@aa81c097:699aadd2

Which is correct, the referenced project is ant based so it is not a gradle project. The gradle plugin should not be active on this project. But it is throwing an exception which prevents the Save function from saving the file.

**Comment by kelemen** [comment]
Seems as if the classloader is not properly set for an external extension. If this turns out to be the case, then it is a major regression and will probably release a fix this week.

The other issue you have mentioned is unrelated and was solved recently: #294.

**Comment by kelemen** [comment]
I can confirm, that this a serious regression breaking backward compatibility for extensions. I have fixed this in master. May I ask you to build the plugin from the sources and try if it solves your problem? If you can verify that the fix is good for you, I will have another release.

**Comment by sdf-cnicorp** [comment]
Thanks for the quick response. However, I cannot confirm that the fix works, since I am unable to build it on my machine.

I downloaded the source and opened the project in Netbeans, but when I attempt to Build I get an error:
```
* Where:
Build file '/Users/sdf/Downloads/netbeans-gradle-project-master-2/netbeans-gradle-default-models/build.gradle' line: 79

* What went wrong:
A problem occurred evaluating project ':netbeans-gradle-default-models'.
> Could not find method modelBuildersCompileOnly() for arguments [{group=org.codehaus.groovy, name=groovy-all, version=1.8.6}] on project ':netbeans-gradle-default-models'.
```
I am still a newbie when it comes to gradle so I am unable to get this working. I will try the release, once it is available.

**Comment by kelemen** [comment]
Maybe you are using an older version of Gradle. Configure 2.13 as Gradle version to be used.

**Comment by sdf-cnicorp** [comment]
I am still getting an exception with the latest master. See attached log
[messages.log.zip](https://github.com/kelemen/netbeans-gradle-project/files/522486/messages.log.zip)

**Comment by kelemen** [comment]
This is not exactly the same error but I will look into it. With trivial cases, I was not able to reproduce it yet.

**Comment by kelemen** [comment]
It was a stupid mistake of mine. Can you check it again? (you might need to kill the Gradle daemon's after updating, also for convenience I recommend you to bump the version number in the root build.gradle).

**Comment by sdf-cnicorp** [comment]
Looks like you nailed it. No exceptions in the log after startup. Thanks!

**Comment by kelemen** [comment]
Thanks for the verification. I will create a new release today.
